import Banner from "@/components/Banner";
import Container from "@/components/Container";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Modal from "@/components/Modal";
import Navbar from "@/components/Navbar";
import Newsletter from "@/components/Newsletter";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Duka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Header />
        <Banner />
        <Container />
        <Modal />
        <Newsletter />
        <Footer />
      </main>
    </>
  );
}
